# Generated by Django 5.2.5 on 2025-08-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
    ]
