# Generated by Django 5.2.5 on 2025-08-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_venue_facebook_url_venue_instagram_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='instagram_url',
        ),
    ]
