# Generated by Django 5.2.5 on 2025-08-21 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_venue_facebook_url_remove_venue_instagram_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='tiebreak_value',
            new_name='tiebreak_seconds',
        ),
        migrations.AddField(
            model_name='score',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.CharField(blank=True, max_length=2)),
                ('scoring', models.CharField(choices=[('time_then_reps', 'Time (if finished) else Reps'), ('reps', 'Reps'), ('weight', 'Weight')], max_length=20)),
                ('counts_as_event', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.event')),
            ],
            options={
                'ordering': ['event__number', 'order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='score',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eventpart'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('part', 'athlete')},
        ),
        migrations.CreateModel(
            name='EventDivisionSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('tiebreak_label', models.CharField(blank=True, max_length=120)),
                ('description_md', models.TextField(blank=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.division')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_specs', to='core.eventpart')),
            ],
            options={
                'unique_together': {('part', 'division')},
            },
        ),
        migrations.RemoveField(
            model_name='score',
            name='event',
        ),
        migrations.RemoveField(
            model_name='score',
            name='raw_value',
        ),
    ]
