# Generated by Django 5.2.5 on 2025-08-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_tiebreak_value_score_tiebreak_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdivisionspec',
            name='gallery_urls',
            field=models.TextField(blank=True, help_text='Una URL por línea (opcional)'),
        ),
        migrations.AddField(
            model_name='eventdivisionspec',
            name='poster',
            field=models.ImageField(blank=True, upload_to='events/'),
        ),
    ]
